### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by mfouesneau** [maartenbreddels/vaex#1]
Incompatible with python 3. Do you plan to make a version?

**Comment by maartenbreddels** [comment]
It should be, and now is :). I develop in python 2, and didn't have ccmenu running so didn't notice travis was giving an error. Thanks for reporting this, try a new pull.

**Comment by mfouesneau** [comment]
Still not working on python 3.  You have print statements and exception syntax to update. 
Future 3.0.5 is also generating an error.

**Comment by maartenbreddels** [comment]
ok, will look into this asap

**Comment by maartenbreddels** [comment]
fixed
