### ISSUE TITLE
Fails to install with pip

### ISSUE THREAD

**Issue by whyboris** [maartenbreddels/vaex#103]
When installing with `pip install vaex`

`SyntaxError: Missing parentheses in call to 'print'.`

https://github.com/maartenbreddels/vaex/blob/c370061ffc2e6ef5a53896efecc3370020574fb9/docs/source/conf.py#L82

Does not fail when installing with `pip install --pre vaex`

**Comment by maartenbreddels** [comment]
Hi Boris,

I'm surprised that that file is being looked at, but I fixed this in the repo. The next releases should work. Maybe it is an old (or very new) version of pip that is responsible for this, try upgrading or downgrading pip, and let me know if that has an effect.

cheers,

Maarten

**Comment by whyboris** [comment]
Sorry -- I have an alias for `pip` which is `pip3` -- so I'm always running _python_ 3.6+ under my hood.
