### ISSUE TITLE
Links to Gaia Datasets in documentation not correct

### ISSUE THREAD

**Issue by leannep** [maartenbreddels/vaex#104]
In https://github.com/maartenbreddels/vaex/blob/master/docs/source/datasets.ipynb
There are 2 errors: 

1.  'Gaia data release 2 (DR1)'  => Gaia data release 2 (**DR2**)
2. The link to 'Full Gaia DR2 - 1.7 billion rows 1.2TB' points to the  '[Only with radial velocities - 7 million - 5.2GB]' file: gaia-dr2-rv-sort-by-source_id.hdf5  and not the full Gaia DR2 dataset file

**Comment by maartenbreddels** [comment]
Hi Leanne,

Good catch! Thanks for reporting, the docs will be up to date as soon as readthedocs builds it.

cheers,

Maarten
