### ISSUE TITLE
Vaex gui broken with matplotlib 3.x

### ISSUE THREAD

**Issue by mfouesneau** [maartenbreddels/vaex#109]
Since the new matplotlib 3, the GUI cannot be used anymore. 

For instance, simply clicking on the xy plot will raise an issue:
```python
AttributeError: 'AxesSubplot' object has no attribute 'hold'
```
which is because of breaking changes int mpl.

**Comment by maartenbreddels** [comment]
this is fixed in vaex-viz 0.3.1 now

**Comment by mfouesneau** [comment]
How do I install that?

pip uninstall vaex-core vaex-viz vaex-astro vaex-hdf5 
pip install --pre vaex-core vaex-viz vaex-astro vaex-hdf5 

did not work

**Comment by maartenbreddels** [comment]
What do you mean with 'not work', you do not have the fix?

` $ pip install vaex-viz==0.3.1` should work.

**Comment by mfouesneau** [comment]
$ vaex
Traceback (most recent call last):
  File "/Users/fouesneau/bin/vaex", line 11, in <module>
    sys.exit(main())
  File "/Users/fouesneau/.local/lib/python3.6/site-packages/vaex/__main__.py", line 128, in main
    import vaex.ui.main
ModuleNotFoundError: No module named 'vaex.ui'

**Comment by mfouesneau** [comment]
ok I had to manually remove all vaex libs from my site-packages and reinstall it.

**Comment by maartenbreddels** [comment]
Actually, that should have been:
`$ pip install vaex-ui==0.2.1`
But great that it is working, still annoying, those installation issues, maybe pip thought it was installed and didn't do it.
