### ISSUE TITLE
Adding plt.errorbar / plt.scatter on selections

### ISSUE THREAD

**Issue by jhjhagen** [maartenbreddels/vaex#11]
I would like to make a scatterplot with errorbars (like in plt.errorbar) on selections. Can it be implemented?

**Comment by maartenbreddels** [comment]
You can now do ds.evalulate("x", selection="...") so it is easier to do scatterplots and errorbars. I've also added ds.scatter(...) no errorbars for it yet.

**Comment by maartenbreddels** [comment]
Now completely implemented by dc2a431ab97d83fbcd53d9b6aeca1c5a5bff8c10
