### ISSUE TITLE
Open more than one file with same data structure

### ISSUE THREAD

**Issue by bombrun** [maartenbreddels/vaex#12]
In order to use vaex we have to merge files. It will be nice to be able to skip that step by having the option to open more than one file (with the same data structure) when calling vaex.

**Comment by maartenbreddels** [comment]
You can 'merge' them, using [vaex.open_many(...)](http://vaex.astro.rug.nl/latest/api.html#vaex.open_many), for instance:
```
ds = vx.open_many(["set1.hdf5", "set2.hdf5"])
```
Or If you have a file list in a file:
```
with open("many.txt") as f:
    ds = vx.open_many(f.readlines())
```
(And it will skip lines starting with a #

You can also use [concat](http://vaex.astro.rug.nl/latest/api.html#vaex.dataset.DatasetLocal.concat), for instance:
```
ds1 = vx.open("set1.hdf5")
ds2 = vx.open("set2.hdf5")
ds = ds1.concat(ds2)
```

I hope this is what you need, see also:
http://vaex.astro.rug.nl/latest/tutorial_ipython_notebook.html#concatenating-tables

**Comment by bombrun** [comment]
available with vaex.open_many
