### ISSUE TITLE
expressions don't work

### ISSUE THREAD

**Issue by jhidding** [maartenbreddels/vaex#17]
Hi, I tried adding a virtual column in Zeldovich sample data, and get an error message. The same thing happens if I try to create a variable. I have installed Vaex in a virtual-env.

> An unexpected error occured, you may press ok and continue, but the program might be unstable.
> 	
> username: 'johannes'
> program: 'vaex'
> version: '1.0.0-beta.4'
> full name: 'vaex-1.0.0-beta.4'
> arguments: ['/home/johannes/.local/share/workon/vaex/bin/vaex']
> Qt version: '5.8.1'
> architecture: ('64bit', '')
> dist: ('fedora', '25', 'Twenty Five')
> java_ver: ('', '', ('', '', ''), ('', '', ''))
> libc_ver: ('glibc', '2.3.4')
> linux_distribution: ('Fedora', '25', 'Twenty Five')
> mac_ver: ('', ('', '', ''), '')
> machine: 'x86_64'
> node: 'ESLT0041'
> platform: 'Linux-4.9.14-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five'
> processor: 'x86_64'
> python_branch: ''
> python_build: ('default', 'Mar 21 2017 17:21:33')
> python_compiler: 'GCC 6.3.1 20161221 (Red Hat 6.3.1-1)'
> python_implementation: 'CPython'
> python_revision: ''
> python_version: '3.5.3'
> python_version_tuple: ('3', '5', '3')
> release: '4.9.14-200.fc25.x86_64'
> system: 'Linux'
> uname: uname_result(system='Linux', node='ESLT0041', release='4.9.14-200.fc25.x86_64', version='#1 SMP Mon Mar 13 19:26:40 UTC 2017', machine='x86_64', processor='x86_64')
> version: '#1 SMP Mon Mar 13 19:26:40 UTC 2017'
> win32_ver: ('', '', '', '')
> 
> Traceback (most recent call last):
>   File "/home/johannes/.local/share/workon/vaex/lib/python3.5/site-packages/vaex/ui/columns.py", line 77, in setData
>     self.dataset.write_meta()
>   File "/home/johannes/.local/share/workon/vaex/lib/python3.5/site-packages/vaex/dataset.py", line 4382, in write_meta
>     path = os.path.join(self.get_private_dir(create=True), "meta.yaml")
>   File "/home/johannes/.local/share/workon/vaex/lib/python3.5/site-packages/vaex/dataset.py", line 4306, in get_private_dir
>     name = os.path.abspath(self.path).replace("/", "_")[:250]  # should not be too long for most os'es
>   File "/home/johannes/.local/share/workon/vaex/lib64/python3.5/posixpath.py", line 358, in abspath
>     if not isabs(path):
>   File "/home/johannes/.local/share/workon/vaex/lib64/python3.5/posixpath.py", line 64, in isabs
>     return s.startswith(sep)
> AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by maartenbreddels** [comment]
Thanks, that was a bug indeed, test+fix in d4056fae2a9a8033e316dfa56523e22847f7417b
