### ISSUE TITLE
Feature request: 2D line plot

### ISSUE THREAD

**Issue by DougRzz** [maartenbreddels/vaex#27]
Hi,

I have looked at the documentation/code and I don't think a 2D line plot is supported in Vaex.  I would like to plot 100M rows of data from a hdf5 column to create an interactive plot in Jupyter.  I would prefer bqplot to matplotlib if possible.

**Comment by maartenbreddels** [comment]
Hi,

thanks for showing interest. What do you mean by a 2d line plots. Can you be more specific? Would it be 100M different lines? And can you give me an example where this is useful, I'm curious what you have in mind?

cheers,

Maarten

**Comment by DougRzz** [comment]
Hi Maarten, 

Thanks for the quick response. I would like to plot long time histories of data.  A typical hdf5 file would have 100 columns and 100 million rows. I would like to plot maybe 2 or 3 of these columns ( different colour lines for each column)  against  time on the x-axis. The equivalent plot type In matplotlib would be similar to  the plt.plot(x, y, linestyle='-') . I would also like to create virtual channels with the data (statistics, sum, mean, rolling mean etc etc) .   I have been down sampling the data to plot it in jupyter  but it would be nice for the user to be able to zoom into the data interactively. Because the data set cannot fit into memory, I thought maybe Vaex or Dask/Datashader/Holoviews technology could be a good solution. Would Vaex be suitable for this type of application?

Doug

**Comment by maartenbreddels** [comment]
Hi Doug,

ok, I think I now understand what you want. Is the sampling regular? If not, I assume you have a column containing the time, if that is the case, you could do sth like this:
```python
ds.plot1d('t', what='mean(amount)')
```
If it is regularly sampled, I need to think about it, but I have some ideas. 

cheers,

Maarten

**Comment by DougRzz** [comment]
Hi Maarten,

Yes, I have 1 column for time. All other columns are the other data channels that would be plotted against time.  The time samples are not alway regular.

I tried the code below but it didn't give an output.
```
import vaex as vx

dataset = vx.datasets.helmi_de_zeeuw.fetch()

dataset.plot1d("x", what='mean(y)')
```

I have created a Jupyter notebook to better explain what I would like Vaex to do.  I can't attach notebooks to Github issues so I will email it to you.   I would be interested in what you think and whether or not it would be worth implementing in Vaex. 

Thanks, Doug

**Comment by maartenbreddels** [comment]
Yes, feel free to send me by email. Try adding the following magic:
```
%matplotlib inline
```
Or try adding `show=True` to the plot1d command.

**Comment by DougRzz** [comment]
Maarten,  

I have done it!  Thanks very much for your help.  I love the power of expressions in Vaex.  

For reference,
I used this code in the BQplot brush interval callback:

        # expression to find time range (index),  Where 'a' is list of min + max of selected range
        tExpression = "abs(" + str((a[0] + a[1])/2) + " - index) < " + str((a[1]-a[0])/2)
        
        # Save a data selection method 
        price_dataVX.select(tExpression, name='xpos') 
        
        # Create mean of binned data 
        t = price_dataVX.mean("index", binby="index", selection = 'xpos', shape=samplePoints, limits=[a[0],a[1]])
        data = price_dataVX.mean(symbol2, binby="index", selection = 'xpos', shape=samplePoints, limits=[a[0],a[1]])


Cheers,
Doug
![2017-06-22 11-07-15_interactive2dlineplotzoom-vaex_bqplot](https://user-images.githubusercontent.com/3510318/27428930-755dc852-573b-11e7-8459-eccb943a29df.png)

**Comment by maartenbreddels** [comment]
Hi Doug,

thanks for sharing this and your enthousiasm, glad you like using vaex!

cheers,

Maarten
