### ISSUE TITLE
Bug:  'vaex.ext.bqplot' has no attribute 'get_class'

### ISSUE THREAD

**Issue by DougRzz** [maartenbreddels/vaex#28]
Hi,

The plot_bq doesn't seem to work. See code and error message below. There doesn't appear to be a get_class function in the repo.  I have noticed that you mentioned in the code comments that the bqplot in Vaex is experimental so perhaps I should just be using matplotlib for now.  However, the bqplot demo in the 'Billion stars in Jupyter' presentation you did is very impressive!  I tried to replicate it but I can't.  

import vaex as vx
dataset = vx.datasets.helmi_de_zeeuw.fetch() # get a cup of coffee while this downloads
dataset.plot_bq("x", "y", f="log1p", show=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-4b3bf5c6b7fe> in <module>()
----> 1 dataset.plot_bq("x", "y", f="log1p", show=True)

c:\users\doug\documents\github\vaexdr\vaex\vaex\dataset.py in plot_bq(self, x, y, grid, shape, limits, what, figsize, f, figure_key, fig, axes, xlabel, ylabel, title, show, selection, colormap, grid_limits, normalize, grid_before, what_kwargs, type, scales, tool_select, bq_cleanup, **kwargs)
   1991 			 **kwargs):
   1992                 import vaex.ext.bqplot
-> 1993                 cls = vaex.ext.bqplot.get_class(type)
   1994 		plot2d = cls(dataset=self, x=x, y=y, grid=grid, shape=shape, limits=limits, what=what,
   1995                                 f=f, figure_key=figure_key, fig=fig,

AttributeError: module 'vaex.ext.bqplot' has no attribute 'get_class'

**Comment by maartenbreddels** [comment]
Hi,

ah, I see where this snippet comes from, I should update that. Try this:
```python
dataset.plot_widget("Lz", "E", f="log1p")
```
cheers,

Maarten

**Comment by DougRzz** [comment]
It works! Thankyou.

**Comment by maartenbreddels** [comment]
Thanks again, fixed by 002c9c6bf7f52d2b755ef43bb022a91b0f28c3ae
