### ISSUE TITLE
Bug in Windows:  os.system( wget ... ) 

### ISSUE THREAD

**Issue by DougRzz** [maartenbreddels/vaex#29]
Hi,

The fetch() command doesn't seem to work in Windows. For example: 

dataset = nyctaxi_yellow_201x.fetch()

I get an error message because Vaex is looking for a wget utility. Perhaps this utility only exists by standard in Linux and Mac OS.  

In dataset.py  I suggest to replace:
 os.system("wget -c -P %s %s" % (os.path.join(data_dir, self.subdir), url))

with something like:
import wget
wget.download(self.url_list[i], os.path.join(data_dir, self.subdir))

I cloned the project and attempted to implement it but I couldn't get it to work.  I just get an error.   HTTPError: HTTP Error 403: Forbidden. More work required....

**Comment by maartenbreddels** [comment]
Did you try another dataset? would that work, it seems the NY taxi dataset was removed.

**Comment by DougRzz** [comment]
Thanks for the tip. Using another dataset and changing your code slightly, this command now works in Windows:
dataset = vx.datasets.helmi_de_zeeuw.fetch()

I need to work out how to do pull requests from Github desktop.  Hopefully, I'll figure it out tomorrow evening. 

Basically I changed the code in the download function to:

# code = os.system(self.wget_command(0))
import wget
fileName = wget.download(self.url, os.path.join(data_dir, os.path.basename(self.url)))			

If you chose to use this code, this would add wget as another python module dependency for Vaex.

**Comment by maartenbreddels** [comment]
I've used urllib.urlretrieve as a fallback.
