### ISSUE TITLE
Non conda dependencies

### ISSUE THREAD

**Issue by SylvainCorlay** [maartenbreddels/vaex#3]
I was looking at making a conda recipe for vaex. The following dependecies are not available on the main conda channels

```
aplus
attrdict
cachetools
jprops
kapteyn
progressbar2
```

**Comment by maartenbreddels** [comment]
Yes, I started here: https://github.com/conda-forge/staged-recipes/pull/1600
kapteyn I can do myself (it's code from our institute), the others I don't know what to do with, it is normal that a non-author writes these recipes?

**Comment by SylvainCorlay** [comment]
Yes. Most of the recipes are written by independent packagers who need
them, although it is always better if the author is involved. For example I
contributed the gtest recipe.

On the attrdict, we have one in traitlets called Bunch. I don't know if we
really consider it public API though.

**Comment by maartenbreddels** [comment]
Ok, i'll get to it then. I can remove attrdict, thinking of getting rid of jprops, but aplus, cachetools and kapteyn are needed. progressbar2 I'm not sure of.

**Comment by maartenbreddels** [comment]
Ok, it's in conda forge :smile:! pyqt is not listed as dependency yet, I'll think I'll add that later. Also the requests dep is missing when you want the gui, so for full vaex with gui:
```
conda install -c conda-forge vaex requests pyqt
```
Otherwise just vaex should do.
