### ISSUE TITLE
Rotation in 3d?

### ISSUE THREAD

**Issue by rieder** [maartenbreddels/vaex#30]
Can add_virtual_columns_rotation also work for three dimensions, rotating over theta and phi? Or is it necessary to do this in steps?

**Comment by rieder** [comment]
Hmm, probably ```add_virtual_columns_matrix3d``` can do this...

**Comment by maartenbreddels** [comment]
True, maybe a rotation3d could help here.. but I'd have to think about how to define the angles etc, too many conventions :).
