### ISSUE TITLE
Broken lightboxes on website

### ISSUE THREAD

**Issue by jamesscottbrown** [maartenbreddels/vaex#32]
The lightboxes on [the project website](http://vaex.astro.rug.nl/) are broken, because they contain ``a`` tags with a ``href`` attribute that does not include ``image/`` (e.g. ``href="nyc_taxi_full.png"`` rather than ``href="image/nyc_taxi_full.png"``).

**Comment by maartenbreddels** [comment]
Thanks a lot! Fixed by 3ebf2502cd1a1b89b1d2736d8a3e5b61e4380f06.
