### ISSUE TITLE
Dealing with nans 

### ISSUE THREAD

**Issue by JovanVeljanoski** [maartenbreddels/vaex#34]
Hi, 

First of all, thanks for this awesome package. May I ask, can you please add a way of dealing with nans (or missing values) in the dataset, especially if the columns are a numeric type of some sort. This could be dropping columns or rows that have nans, or maybe imputing a user defined values. 

Thank you,
J.

**Comment by maartenbreddels** [comment]
ds.fillna and ds.dropna / ds.select_non_missing are support (still in packages, soon in master)
