### ISSUE TITLE
Installation error in sampy.py through pip

### ISSUE THREAD

**Issue by Mixpap** [maartenbreddels/vaex#36]
I was trying to install Vaex through pip (9.0.1). After installing all the requirements an error occurred in sampy installation.
Although its not a Vaex issue i couldn't find the sampy package to try to fix or raise an issue, so i attended here.

> Collecting sampy>=1.2 (from vaex)
  Downloading sampy-1.2.1.tar.gz (63kB)
    100% |████████████████████████████████| 71kB 176kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LgDLkG/sampy/setup.py", line 3, in <module>
        import sampy
      File "sampy.py", line 914, in <module>
        class HTTPSConnection(httplib.HTTPConnection):
      File "sampy.py", line 921, in HTTPSConnection
        ssl_version=ssl.PROTOCOL_SSLv3, strict=None):
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

I updated urllib3 (1.22), requests (2.6.0), pip (9.0.1) etc packages as mentioned in other sources.

**Comment by maartenbreddels** [comment]
Hi,

I think it should work when you install the latest beta using the --pre flag:
```
$ pip install --pre vaex
```
sampy is now part of astropy.

**Comment by Mixpap** [comment]
That solved it, 
Thank you :)

**Comment by maartenbreddels** [comment]
Great!

**Comment by g07kore** [comment]
worked for me too! Thanks.

**Comment by maartenbreddels** [comment]
👍
