### ISSUE TITLE
evaluate casts data types through floats messing with long int

### ISSUE THREAD

**Issue by mfouesneau** [maartenbreddels/vaex#37]
https://github.com/maartenbreddels/vaex/blob/2924541ec199a6852a78d1d5689695430d27c525/vaex/export.py#L361

evaluates does not keep the precision of the values and seems to cast values to float/double precision during the process.

**Comment by maartenbreddels** [comment]
That should not happen, which version are you using?

**Comment by mfouesneau** [comment]
version gives me 1.0.0-beta.4

**Comment by maartenbreddels** [comment]
Doing the following:
```python
import vaex as vx
import numpy as np
ds = vx.from_arrays(f8=np.arange(10, dtype='f8'), i8=np.arange(10, dtype='i8'))
ds.evaluate('f8').dtype, ds.evaluate('i8').dtype, 
```
Gives me:
```bash
(dtype('float64'), dtype('int64'))
```
Can you check if you get the same?
If you don't get that, can you update to beta 6 and let me know if that fixes it?

**Comment by mfouesneau** [comment]
In [1]: import vaex as vx
   ...: import numpy as np
   ...: ds = vx.from_arrays(f8=np.arange(10, dtype='f8'), i8=np.arange(10, dtype='i8'))
   ...: ds.evaluate('f8').dtype, ds.evaluate('i8').dtype, 
   ...: 
Out[1]: (dtype('float64'), dtype('float64'))

**Comment by mfouesneau** [comment]
How do I install the new beta? conda-forge does not have it and pip seems to want 0.3.10 something

**Comment by mfouesneau** [comment]
The test above works, but now `from_arrays` is not working anymore. What's the change in the API so I can test on my actual data?

**Comment by maartenbreddels** [comment]
Conda-forge has beta6 (see https://anaconda.org/conda-forge/vaex), and installing from pip you indeed should use the `--pre` flag.
And indeed, that was a breaking api change, that was a bad decision to take a name argument. 
I plan to keep a public changelog after the 1.0 release, changes are prefixed in the commit msg'es by 'changes:' for now, new features with 'new:' and fixes with 'fix:'.

Please let me know if you've managed to get this working.
(Sorry for the late reaction, I was traveling)

**Comment by mfouesneau** [comment]
yes I looked at the source to figure the changes in some places. It works!

FYI, the healpix_plot doc needs updates or the code needs to be generalized. It currently imposes Gaia conventions that are not healpy defaults. (nested not ring for instance). I can open an issue if you need.

**Comment by maartenbreddels** [comment]
Please do, we can discuss further.
