### ISSUE TITLE
Cleaning prints

### ISSUE THREAD

**Issue by mfouesneau** [maartenbreddels/vaex#43]
https://github.com/maartenbreddels/vaex/blob/2924541ec199a6852a78d1d5689695430d27c525/vaex/dataset.py#L1562

Some debugging left overs I suppose. Can you clean?

Thanks

**Comment by maartenbreddels** [comment]
Yes indeed, that method needs a good review anyway!

**Comment by maartenbreddels** [comment]
Cleaned up in branch packages (soon in master), it can use a speedup in some parts though.
