### ISSUE TITLE
Tutorial run through issues on Windows 10

### ISSUE THREAD

**Issue by apiszcz** [maartenbreddels/vaex#59]
Platform, Windows 10, Python 3.5
The same codes works correctly according to tutorial on CENTOS/LINUX

#1 'warning'
```
>>> import vaex
>>> ds = vaex.example()
lib\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

NOTE
```
>>> ds.get_column_names()
['E', 'FeH', 'L', 'Lz', 'random_index', 'vx', 'vy', 'vz', 'x', 'y', 'z']

>>> ds.max('x')
array(271.365997)

```

#2 'Is this due to an installation error'?
```
import vaex
ds = vaex.example()  # open the example dataset provided with vaex
ds[ds.x < 0]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-bd4c28c4abd5> in <module>()
      1 import vaex
      2 ds = vaex.example()  # open the example dataset provided with vaex
----> 3 ds[ds.x < 0]

AttributeError: 'Hdf5MemoryMapped' object has no attribute 'x'
```

**Comment by apiszcz** [comment]
Installation issues, most resolved.

**Comment by maartenbreddels** [comment]
You are quicker than me, I assume you didn't use the `--pre` flag for pip?

**Comment by apiszcz** [comment]
I am working on understanding the dependencies separately so I'm loading
one thing at a time.

I have dateutil 2.6.1 not sure why this is happending.

ERROR:MainThread:vaex:issue loading ml
Traceback (most recent call last):
  File "c:\\test\lib\vaex\__init__.py", line 436, in <module>
    add_namespace = entry.load()
  File "c:\\test\lib\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "c:\\test\lib\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\\test\lib\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil>=2.0' distribution
was not found and is required by matplotlib
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "c:\\test\lib\vaex\__init__.py", line 444, in <module>
    add_namespace = entry.load()
  File "c:\\test\lib\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "c:\\test\lib\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\\test\lib\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil>=2.0' distribution
was not found and is required by matplotlib
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "c:\\test\lib\vaex\__init__.py", line 444, in <module>
    add_namespace = entry.load()
  File "c:\\test\lib\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "c:\\test\lib\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\\test\lib\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aplus' distribution was not found
and is required by vaex-core
c:\\test\lib\h5py\__init__.py:36: FutureWarning: Conversion of the second
argument of issubdtype from `float` to `np.floating` is deprecated. In
future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by apiszcz** [comment]
aplus was missing in last stack trace

**Comment by maartenbreddels** [comment]
Odd, there have been quite some changes now, before vaex was a single package, now it's multiple.
What could help is this:
```
$ pip uninstall vaex vaex-core
$ pip install vaex-core vaex-viz vaex-hdf5
```
That should most likely work. Feedback is appreciated.

**Comment by apiszcz** [comment]
Getting closer, my setuptools was old, causing the prior set of issues.

viz was installed, hmm


---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-fc6c0b956f6e> in <module>()
     11 ds.mean(ds.r, binby=[ds.x, ds.y], shape=32, limits=[-10, 10]) # or
2d
     12 ds.count(ds.r, binby=[ds.x, ds.y], shape=32, limits=[-10, 10]) # or
2d counts/histogram
---> 13 ds.plot(ds.x, ds.y, show=True);  # make a plot quickly

C:\test\lib\vaex\dataset.py in wrap(*args, **kwargs)
     52 def _requires(name):
     53         def wrap(*args, **kwargs):
---> 54                 raise RuntimeError('this function is wrapped by a
placeholder, you probably want to install vaex-'+name)
     55         return wrap
     56

RuntimeError: this function is wrapped

**Comment by apiszcz** [comment]
I did the install for all the packages per your documentation.
Thank you for creating and sharing this body of work, I am hoping to
compare memory and performance with datashader.

**Comment by maartenbreddels** [comment]
See also the dicussion here: https://github.com/bokeh/datashader/issues/310 but would be happy to see your findings. There has been a change in the underlying c code that may have impacted performance (if any, most likely negative) and I did not benchmark it again, although I plan to do so next week.
