### ISSUE TITLE
Package availability for windows

### ISSUE THREAD

**Issue by thdeltei** [maartenbreddels/vaex#6]
It would be great if this package would also be available for windows on conda

```
>conda install -c conda-forge vaex
Fetching package metadata ...........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - vaex
```

I tried to install it using the `pip install` command but it failed with some compilation error, setuptools did not find my c++ compiler on the machine.

**Comment by maartenbreddels** [comment]
yes, atm it doesn't have priority (say the next ~3 weeks). But I I had it running on windows once, some changes to the extension are needed. Precompiled anaconda packages/wheels would of course be the best. If you have time for this I'm happy to assist, otherwise it may take a while.

**Comment by thdeltei** [comment]
no problem, I got started on a linux machine instead. Yes, that's always the problem with c++ dependencies, especially getting them compiled on windows can be tricky. I currently don't have the bandwidth (or the expertise for that matter 😄 ) to generate the windows c++ wheels, but happy to test them on windows 10 and windows server 2012 if that helps.

**Comment by maartenbreddels** [comment]
The current git version of vaex seems to work for most parts on windows, I didn't test if that well though. Conda packages should hopefully be build soon.

**Comment by maartenbreddels** [comment]
[Anaconda package is available](https://anaconda.org/conda-forge/vaex/)

Install with:
```
conda install -c conda-forge vaex
```
