### ISSUE TITLE
sky position visualization looks funny 

### ISSUE THREAD

**Issue by andersdot** [maartenbreddels/vaex#75]
I'm using vaex to visualize Gaia data, and I can't get the visualization of stars on the sky to look right

When I do a scatter plot of the dataset.values it looks correct, but doing

ds.plot(ds.ra, ds.dec) 

gives a funny cross shape on the sky (see cell 9 vs cell 10 in the following notebook)

https://github.com/andersdot/gaiaDR2/blob/master/playVaex.ipynb

**Comment by maartenbreddels** [comment]
It took me a while to figure out what could go wrong, but I figured it out. Fits stores in big endian format, while most cpus (intel) are little endian. Vaex should take this into account, but for some reason is missing this case, and this is a bug I should fix.
I have two workarounds.
1) (recommended)
Convert to hdf5, by doing `ds.export_hdf5('table.hdf5')` or on the cmd line
```
$ vaex convert file input.fits output.hdf5
```
2)
Force vaex to make a calculation that will lead to the data becoming little endian
`ds.plot(ds.ra*1, ds.dec*1, f='log')`

I'll keep this open till I have this fixed.

**Comment by maartenbreddels** [comment]
Btw, you can also download Gaia data here:
https://drive.google.com/drive/folders/1fuQQFZpjHMiLpslwVBDenT1opgwos78E
I haven't yet described it yet though.
