### ISSUE TITLE
ds.columns should return a list of  strings....

### ISSUE THREAD

**Issue by datascienceit** [maartenbreddels/vaex#81]
ds.columns() should get you a slit of strings so it will be easy to combine it with other packages, tools and applications.
The ds.columns.keys() is tiresome and unique to vaex.

**Comment by maartenbreddels** [comment]
I agree, but I cannot simply change the API without breaking a gazillion codes :)

**Comment by maartenbreddels** [comment]
Btw, there is get_column_names(...) check that out.
