### ISSUE TITLE
printing a line when running plotting

### ISSUE THREAD

**Issue by datascienceit** [maartenbreddels/vaex#85]
[](https://www.dropbox.com/s/2kw6uxxs29pxlzw/vaex-plot-bug.jpg?dl=0)
when using plot1d
[Not printing the <matplotlib...>

**Comment by JovanVeljanoski** [comment]
This is a due to matplotlib not vaex. Same would happen if you do pyplot.hist(..).

To not get that line, simply put 
pyplot.show()

**Comment by maartenbreddels** [comment]
or end with ;
