### ISSUE TITLE
 shape argument in ds.plot

### ISSUE THREAD

**Issue by jhjhagen** [maartenbreddels/vaex#86]
ds.plot is not working properly when different shapes in x and y are needed.

ds.plot('x', 'y', shape=10, limits=[[-1,1],[-1,1]], f='log10')
plt.show()

![image](https://user-images.githubusercontent.com/23260614/40164982-3ebf3b54-59bb-11e8-9531-09030e60ee3b.png)

ds.plot('x', 'y', shape=[10,4], limits=[[-1,1],[-1,1]], f='log10')
plt.show()

![image](https://user-images.githubusercontent.com/23260614/40165008-48747e20-59bb-11e8-9285-bcc80005a887.png)

Both plot have 10 bins in both x and y direction.

**Comment by maartenbreddels** [comment]
Thanks, also fixed.
