### ISSUE TITLE
ds.plots multiple plots in 1 figure

### ISSUE THREAD

**Issue by jhjhagen** [maartenbreddels/vaex#87]
Requesting more than two plots will raise an error:

ds.plot([['x','y'],['x','z']], shape=10, limits=[[-1,1],[-1,1]], f='log10')
plt.show()

![image](https://user-images.githubusercontent.com/23260614/40165242-c329d44e-59bb-11e8-8173-10636aa8c84b.png)

ds.plot([['x','y'],['x','z'],['y','z']], shape=10, limits=[[-1,1],[-1,1]], f='log10')
plt.show()

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-51-961b8a21153e> in <module>()
      2 plt.show()
      3 
----> 4 ds.plot([['x','y'],['x','z'],['y','z']], shape=10, limits=[[-1,1],[-1,1]], f='log10')
      5 plt.show()

/net/gaia/data/users/breddels/python/anaconda3/lib/python3.6/site-packages/vaex/viz/mpl.py in plot(self, x, y, z, what, vwhat, reduce, f, normalize, normalize_axis, vmin, vmax, shape, vshape, limits, grid, colormap, figsize, xlabel, ylabel, aspect, tight_layout, interpolation, show, colorbar, colorbar_label, selection, selection_labels, title, background_color, pre_blend, background_alpha, visual, smooth_pre, smooth_post, wrap, wrap_columns, return_extra, hardcopy)
    764             else:
    765                 subplot_index = 0
--> 766             extend = np.array(xlimits[subplot_index][-2:]).flatten()
    767             #   extend = np.array(xlimits[i]).flatten()
    768             logger.debug("plot rgrid: %r", plot_rgrid.shape)

IndexError: list index out of range
![image](https://user-images.githubusercontent.com/23260614/40165247-c7a79dda-59bb-11e8-846c-e3b344094cf0.png)

**Comment by maartenbreddels** [comment]
This is fixed now

**Comment by jhjhagen** [comment]
Hi,

Thanks again. I have a minor comment about how the limits argument work if you have multiple subplots, let's say 3 subplots. Then:

1) limits=[-1,1] # Will set the same x-limits as y-limits (and for each subplot)
2) limits=[[-1,1],[-2,2],[-3,3]] # Will set the same x-limits as y-limits per subplot, though different for each subplot
3) limits=None # Automatically computes (different) x- and y-limits for each subplot individually.

Is this how it should work?
I am wondering: wouldn't it be useful to also implement something like this:

4) limits=[[-1,2],[-2,3]] # NOT WORKING: I want to set xlim and ylim (identical for each subplot)

or else arguments xlimits and ylimits. So this is similar to (1), though just different x- and y-limits, whereas in (1): xlimits=ylimits.
I could already achieve this by setting:

5) limits=[[[-1,2],[-2,3]],[[-1,2],[-2,3]],[[-1,2],[-2,3]]]  Will set x-limits and y-limits (identical for each subplot)

Though this is not a nice solution (especially for many subplots).
