### ISSUE TITLE
scatter labels in ds.scatter

### ISSUE THREAD

**Issue by jhjhagen** [maartenbreddels/vaex#88]
I understand the idea of the label argument in ds.scatter (although I do not understand the output and error in my example [all z values should be tiny]):

_ds.scatter('x','y', selection='abs(z)<0.000001', label='z')_

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-56828c111aa1> in <module>()
----> 1 ds.scatter('x','y', selection='abs(z)<0.000001', label='z')

/net/gaia/data/users/breddels/python/anaconda3/lib/python3.6/site-packages/vaex/viz/mpl.py in scatter(self, x, y, xerr, yerr, cov, corr, s_expr, c_expr, selection, length_limit, length_check, label, xlabel, ylabel, errorbar_kwargs, ellipse_kwargs, **kwargs)
    208         label_values = self.evaluate(label)
    209         for i, label_value in enumerate(label_values):
--> 210             plt.annotate(label_value, (x_values[i], y_values[i]))
    211     xerr_values = None
    212     yerr_values = None

IndexError: index 14 is out of bounds for axis 0 with size 14
![image](https://user-images.githubusercontent.com/23260614/40165955-9bbb5bec-59bd-11e8-9355-33284f38aa7f.png)

Though, the label argument in ds.plot1d has a different meaning:

_ds.plot1d('x', label='x', selection='abs(z)<0.001')
ds.plot1d('y', label='y', selection='abs(z)<0.001')
plt.legend()
plt.show()_

![image](https://user-images.githubusercontent.com/23260614/40165636-c7dadb86-59bc-11e8-872f-8d4898223833.png)

Wouldn't it be nice to add a similar argument to ds.scatter, with the same output as the following code:

_s=ds.scatter('x','y', selection='abs(z)<0.001')
s.set_label('dsa1')
s=ds.scatter('x','y', selection='abs(z)<0.0001')
s.set_label('dsa2')
plt.legend()
plt.show()_

![image](https://user-images.githubusercontent.com/23260614/40165474-5c2823b2-59bc-11e8-93fc-e4799c7962fd.png)

**Comment by maartenbreddels** [comment]
Thanks again, fixed!
